server:
  port: 8080
  forward-headers-strategy: framework

spring:
  application:
    name: ticketapp-bff
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/ticketapp}
    username: ${DB_USER:ticketapp}
    password: ${DB_PASSWORD:ticketapp}
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

logging:
  level:
    root: INFO
    com.ticketapp: DEBUG
